<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
	<PropertyGroup>
		<Authors>fair-coder</Authors>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
		<Title>fair main extension</Title>
		<Product>fair main extension</Product>
		<Description>fair main extension</Description>
		<Copyright>@2024 freecoder2024. All rights reserved.</Copyright>
		<Version>8.0.0</Version>
	</PropertyGroup>
  <ItemGroup>
    <Content Remove="bundleconfig.json" />
  </ItemGroup>




  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\fair.extensions.shared\fair.extensions.shared.csproj" />
    <ProjectReference Include="..\fair.ui\fair.ui.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
