<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFrameworks>net8.0-android;net8.0-ios;net8.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net8.0-windows10.0.19041.0</TargetFrameworks>

		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

	</PropertyGroup>
	<PropertyGroup>
		<Authors>fairdao</Authors>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
		<Copyright>@2024 fairdao. All rights reserved.</Copyright>
		<Title>fair maui client</Title>
		<Product>fair maui</Product>
		<Description>fair maui client</Description>
		<PackageProjectUrl>https://fair-dao.com/</PackageProjectUrl>
		<RepositoryUrl>https://github.com/fair-dao/fair</RepositoryUrl>
		<PackageIcon>logo.png</PackageIcon>
		<AssemblyName>fairdao.maui.shared</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.11" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="8.0.82" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebView.Maui" Version="8.0.82" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="8.0.82" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.0" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Plugin.Maui.Audio" Version="3.0.1" />
		<PackageReference Include="sqlite-net-pcl" Version="1.8.116" />
		<PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="2.1.2" />
		<PackageReference Include="SQLitePCLRaw.core" Version="2.1.2" />
		<PackageReference Include="SQLitePCLRaw.provider.dynamic_cdecl" Version="2.1.2" />

		<PackageReference Include="SQLitePCLRaw.provider.sqlite3" Version="2.1.2" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-android'">
		<PackageReference Include="SQLitePCLRaw.lib.e_sqlite3.android" Version="2.1.2">
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\fairdao.extensions.shared\fairdao.extensions.shared.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Platforms\Android\FairdaoMainActivity.cs">
			<ExcludeFromCurrentConfiguration>false</ExcludeFromCurrentConfiguration>
		</Compile>
	</ItemGroup>


</Project>
