<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="8.0.10" />
		<PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.10" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" Version="4.*-*" />
		<PackageReference Include="Microsoft.FluentUI.AspNetCore.Components.Icons" Version="4.*-*" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="Components\NavMenu.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	  <Content Update="Components\NotificationCenter.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	  <Content Update="Components\NotificationCenterPanel.razor">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	  </Content>
	</ItemGroup>

</Project>
