<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<WasmEnableSIMD>false</WasmEnableSIMD>
		<ImplicitUsings>enable</ImplicitUsings>
		<CompressionEnabled>false</CompressionEnabled>
		<Authors>fair-coder</Authors>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<PackageLicenseExpression>MPL-2.0</PackageLicenseExpression>
		<Title>fair wallet html5</Title>
		<Product>fair wallet</Product>
		<Description>fair wallet html5 client</Description>
		<Copyright></Copyright>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.1" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.1" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\fair.extensions.main\fair.extensions.main.csproj" />
	</ItemGroup>

</Project>
